<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\AdminController;
use Illuminate\Support\Facades\Route;
use App\Http\Middleware\AdminMiddleware;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CategoryController;

Route::get('/', function () {
    return view('welcome');
});

// Public route to show products (optional)
Route::get('/products', [ProductController::class, 'index'])->name('products.index');

// Dashboard for authenticated and verified users (regular users)
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

// Profile routes for authenticated users
Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

// Admin routes protected by 'auth' and 'admin' middleware

Route::middleware(['auth', 'admin'])->group(function () {
    // Admin dashboard
    Route::get('/admin', [AdminController::class, 'index'])->name('admin.dashboard');

    // Product management CRUD routes (create, read, update, delete)
    Route::resource('products', ProductController::class)->except(['index']);
});

// test:
// Route::middleware(['auth', 'admin'])->get('/admin', [AdminController::class, 'index'])->name('admin.dashboard');


// test:
/*
Route::get('/test-admin', function () {
    return 'Admin route works!';
})->middleware([AdminMiddleware::class]);
*/

// Just for testing the alias: (this alias doesnt work)
// Route::middleware(['auth', 'admin'])->get('/admin', [AdminController::class, 'index'])->name('admin.dashboard');


Route::middleware(['auth', 'admin'])->resource('categories', CategoryController::class);

// Auth routes generated by Laravel Breeze or Jetstream
require __DIR__ . '/auth.php';
